"""M-6 (CWE-497): GET /metrics must not be world-readable.

The policy itself is tested in shared/tests/test_metrics_auth.py; what these
tests pin is that feedback_billing actually *applies* it. This service is the
odd one out — its /metrics route is generated by
prometheus-fastapi-instrumentator rather than hand-written, so the gate is
attached as a route dependency. That is exactly the kind of wiring that gets
dropped by a later `.expose(...)` edit, hence tests against the live app.

The default instrumentator metrics are also what makes the leak worth caring
about here: they enumerate every route the service serves, with status-code and
latency distributions attached.
"""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from app.config import settings
from app.main import app

TOKEN = "unit-test-metrics-token-0123456789"


@pytest.fixture()
def client() -> TestClient:
    return TestClient(app, raise_server_exceptions=False)


def test_correct_bearer_token_gets_metrics(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(settings, "metrics_token", TOKEN)
    # Generate at least one series first — a 200 that returned nothing would
    # pass a status-only assertion while having broken the scrape.
    client.get("/")

    resp = client.get("/metrics", headers={"Authorization": f"Bearer {TOKEN}"})

    assert resp.status_code == 200
    assert resp.headers["content-type"].startswith("text/plain")
    assert "http_request" in resp.text


def test_wrong_bearer_token_is_rejected(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(settings, "metrics_token", TOKEN)
    resp = client.get("/metrics", headers={"Authorization": "Bearer not-the-token"})

    assert resp.status_code == 401
    assert resp.headers["www-authenticate"] == "Bearer"
    assert "http_request" not in resp.text


def test_missing_authorization_header_is_rejected(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(settings, "metrics_token", TOKEN)
    assert client.get("/metrics").status_code == 401


def test_non_ascii_authorization_header_is_rejected_not_a_500(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Starlette decodes header bytes as latin-1, so a non-ASCII header used to
    be a trivially reachable 500 in a naive constant-time comparison. Sent as
    raw bytes because httpx refuses to encode a non-ASCII str header at all —
    a real client on the wire has no such scruples."""
    monkeypatch.setattr(settings, "metrics_token", TOKEN)
    resp = client.get("/metrics", headers={"Authorization": b"Bearer \xff\xfe"})

    assert resp.status_code == 401


def test_unset_token_outside_production_stays_open(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Local dev, docker-compose and CI scrape with no METRICS_TOKEN set; turning
    the gate on must not have broken them."""
    monkeypatch.setattr(settings, "metrics_token", "")
    monkeypatch.setattr(settings, "app_env", "test")

    assert client.get("/metrics").status_code == 200


def test_unset_token_in_production_fails_closed(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """404, not 403: an unauthenticated prober should not learn that the
    endpoint exists. And a response, not a boot crash — a forgotten token must
    never turn a rolling deploy into an outage."""
    monkeypatch.setattr(settings, "metrics_token", "")
    monkeypatch.setattr(settings, "app_env", "production")

    resp = client.get("/metrics")

    assert resp.status_code == 404
    assert "http_request" not in resp.text
